[workspace]
resolver = "2"
members = ["firmware"]

[profile.dev]
debug = true
lto = true
opt-level = "z"
incremental = true

[profile.release]
debug = false
lto = true
opt-level = 2
incremental = true
